apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-deployment
spec:
  selector:
    matchLabels:
      app: quiz-app
  replicas: 2
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - name: quiz-app
          image: skanarul/quizapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: quizapp-service
spec:
  selector:
    app: quiz-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
